package com.autoever.poc.common;

/**
* Generated by JDT StreamBase Client Templates (Version: 11.0.0).
*
* All custom java simple functions must live in a public Java class as a public static method.
* Custom Java simple functions can be accessed by the simple form of calljava in any expression
* except in aggregate functions.
* They may also be aliased for use as if that function were embedded
* in your StreamBase Application.
* <p>
* For in-depth information on implementing a StreamBase simple function, please see some
* related topics from "Developing StreamBase Custom Functions" in the StreamBase 
* documentation.
* <p>
*/
public class ThreadUtil {

	/**
	* A StreamBase Simple Function. Use this function
	* in StreamBase expressions using the <em>calljava</em> function, or 
	* by an assigned alias. It can then be called directly 
	* using the alias name instead of using calljava().
	*/
	public static long getThreadId() {
		return java.lang.Thread.currentThread().getId();
	}

}
